@extends('layouts.app')
@section('title', 'Audit Log | HRS Kampus')
@section('content')
    <div class="flex flex-col justify-between gap-4 md:flex-row md:items-end">
        <div><p class="text-sm font-semibold text-brand-600">Keamanan</p><h1 class="mt-1 text-3xl font-semibold">Audit Log</h1><p class="mt-2 text-sm text-slate-500">Riwayat perubahan data pegawai, payroll, dan keamanan akun.</p></div>
        <form method="GET" class="flex gap-2"><select name="event" class="rounded-xl border border-slate-300 px-4 py-2.5 text-sm"><option value="">Semua aktivitas</option>@foreach (['employee.created' => 'Pegawai dibuat', 'employee.updated' => 'Pegawai diubah', 'payroll.updated' => 'Payroll diubah', 'payroll.finalized' => 'Payroll difinalkan', 'payroll_period.deleted' => 'Periode dihapus', 'password.reset' => 'Password direset', 'password.changed' => 'Password diganti'] as $value => $label)<option value="{{ $value }}" @selected($event === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form>
    </div>
    <div class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Waktu</th><th class="px-5 py-4">Pelaku</th><th class="px-5 py-4">Aktivitas</th><th class="px-5 py-4">Perubahan</th><th class="px-5 py-4">IP</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($auditLogs as $log)<tr class="align-top"><td class="whitespace-nowrap px-5 py-4">{{ $log->created_at->format('d/m/Y H:i:s') }}</td><td class="px-5 py-4"><span class="font-semibold">{{ $log->actor?->name ?? 'Sistem' }}</span><br><span class="text-xs text-slate-400">{{ $log->actor?->email }}</span></td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{{ $log->event }}</span><p class="mt-2 text-slate-600">{{ $log->description }}</p></td><td class="max-w-md px-5 py-4"><details><summary class="cursor-pointer font-semibold text-brand-700">Lihat detail</summary><div class="mt-2 grid gap-2 text-xs"><div><span class="font-semibold">Sebelum:</span><pre class="mt-1 whitespace-pre-wrap rounded-lg bg-red-50 p-2">{{ json_encode($log->old_values, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></div><div><span class="font-semibold">Sesudah:</span><pre class="mt-1 whitespace-pre-wrap rounded-lg bg-emerald-50 p-2">{{ json_encode($log->new_values, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></div></div></details></td><td class="whitespace-nowrap px-5 py-4 text-slate-500">{{ $log->ip_address ?: '-' }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">Belum ada aktivitas tercatat.</td></tr>@endforelse</tbody></table></div>
        <div class="border-t border-slate-100 px-5 py-4">{{ $auditLogs->links() }}</div>
    </div>
@endsection
