@extends('layouts.app')
@section('title', 'Laporan Perjalanan Dinas | HRS Kampus')
@section('content')
    <div><p class="text-sm font-semibold text-brand-600">Ruang kerja pegawai</p><h1 class="mt-1 text-3xl font-semibold">Laporan Perjalanan Dinas</h1><p class="mt-2 text-sm text-slate-500">Terima penugasan dari kampus dan laporkan hasil perjalanan setelah kegiatan selesai.</p></div>

    <section class="mt-7 grid gap-5">
        @forelse ($businessTrips as $businessTrip)
            <article class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                <div class="flex flex-col justify-between gap-4 border-b border-slate-100 p-6 md:flex-row md:items-start"><div><div class="flex flex-wrap items-center gap-3"><h2 class="text-lg font-semibold">{{ $businessTrip->title }}</h2><span @class(['rounded-full px-3 py-1 text-xs font-semibold', 'bg-amber-50 text-amber-700' => $businessTrip->status === 'assigned', 'bg-sky-50 text-sky-700' => $businessTrip->status === 'accepted', 'bg-red-50 text-red-700' => $businessTrip->status === 'rejected', 'bg-brand-50 text-brand-700' => $businessTrip->status === 'reported'])>{{ $businessTrip->statusLabel() }}</span></div><p class="mt-2 text-sm text-slate-500">{{ $businessTrip->destination }} · {{ $businessTrip->start_date->locale('id')->translatedFormat('d F Y') }}–{{ $businessTrip->end_date->locale('id')->translatedFormat('d F Y') }}</p></div><a href="{{ route('business-trips.show', $businessTrip) }}" class="text-sm font-semibold text-brand-700">Lihat detail</a></div>
                <div class="grid gap-5 p-6 lg:grid-cols-[1fr_auto]"><div><p class="text-sm leading-6 text-slate-600">{{ $businessTrip->purpose }}</p><dl class="mt-4 flex flex-wrap gap-x-8 gap-y-3 text-sm"><div><dt class="text-xs text-slate-400">Transportasi</dt><dd class="mt-1 font-medium">{{ $businessTrip->transportation ?: '-' }}</dd></div><div><dt class="text-xs text-slate-400">Uang perjalanan</dt><dd class="mt-1 font-medium">Rp {{ number_format((float) $businessTrip->allowance, 0, ',', '.') }}</dd></div><div><dt class="text-xs text-slate-400">Pemberi tugas</dt><dd class="mt-1 font-medium">{{ $businessTrip->assignedBy->name }}</dd></div></dl></div>
                    @if ($businessTrip->status === 'assigned')
                        <div class="flex flex-col gap-2 sm:min-w-56"><form method="POST" action="{{ route('business-trips.response.update', $businessTrip) }}">@csrf @method('PUT')<input type="hidden" name="decision" value="accepted"><button class="w-full rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">Terima Tugas</button></form><form method="POST" action="{{ route('business-trips.response.update', $businessTrip) }}" class="flex flex-col gap-2">@csrf @method('PUT')<input type="hidden" name="decision" value="rejected"><textarea name="rejection_reason" rows="2" required maxlength="2000" placeholder="Alasan penolakan" class="rounded-xl border border-slate-300 px-3 py-2 text-xs"></textarea><button class="rounded-xl border border-red-200 px-4 py-2 text-sm font-semibold text-red-600">Tolak Tugas</button></form></div>
                    @endif
                </div>
                @if (in_array($businessTrip->status, ['accepted', 'reported'], true))
                    <form method="POST" action="{{ route('business-trips.report.update', $businessTrip) }}" enctype="multipart/form-data" class="border-t border-slate-100 bg-slate-50 p-6">@csrf @method('PUT')<h3 class="font-semibold">{{ $businessTrip->status === 'reported' ? 'Perbarui Laporan Perjalanan' : 'Isi Laporan Perjalanan' }}</h3><div class="mt-4 grid gap-4 lg:grid-cols-2"><label class="text-sm font-semibold text-slate-600">Ringkasan kegiatan<textarea name="report_summary" rows="4" required maxlength="5000" class="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm">{{ old('report_summary', $businessTrip->report_summary) }}</textarea></label><label class="text-sm font-semibold text-slate-600">Hasil perjalanan<textarea name="report_result" rows="4" required maxlength="5000" class="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm">{{ old('report_result', $businessTrip->report_result) }}</textarea></label></div><label class="mt-4 block text-sm font-semibold text-slate-600">Catatan tambahan<textarea name="report_notes" rows="2" maxlength="5000" class="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm">{{ old('report_notes', $businessTrip->report_notes) }}</textarea></label><div class="mt-4 grid gap-4 sm:grid-cols-[1fr_auto] sm:items-end"><label class="text-sm font-semibold text-slate-600">Foto dokumentasi <span class="font-normal text-slate-400">(opsional, JPG/PNG/WebP, maks. 5 MB)</span><input type="file" name="report_image" accept="image/jpeg,image/png,image/webp" class="mt-2 block w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-brand-50 file:px-3 file:py-1.5 file:font-semibold file:text-brand-700"></label>@if ($businessTrip->report_image_path)<a href="{{ asset('storage/'.$businessTrip->report_image_path) }}" target="_blank" class="text-sm font-semibold text-brand-700">Lihat foto saat ini</a>@endif</div><button class="mt-4 rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Simpan Laporan</button></form>
                @elseif ($businessTrip->status === 'rejected')
                    <div class="border-t border-red-100 bg-red-50 px-6 py-4 text-sm text-red-700"><strong>Alasan penolakan:</strong> {{ $businessTrip->rejection_reason }}</div>
                @endif
            </article>
        @empty
            <div class="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><h2 class="font-semibold text-slate-600">Belum ada perjalanan dinas</h2><p class="mt-2 text-sm text-slate-400">Penugasan dari Admin/SDM akan muncul di halaman ini.</p></div>
        @endforelse
    </section>
    <div class="mt-6">{{ $businessTrips->links() }}</div>
@endsection
