@extends('layouts.app')
@section('title', 'Master Tanggal Merah | HRS Kampus')
@section('content')
    <a href="{{ route('leave-requests.index') }}" class="text-sm font-semibold text-brand-700">← Cuti & Persetujuan</a><h1 class="mt-3 text-3xl font-semibold">Master Tanggal Merah</h1><p class="mt-2 text-sm text-slate-500">Tanggal di sini otomatis dikecualikan dari perhitungan durasi cuti.</p>
    <div class="mt-6 grid gap-6 lg:grid-cols-[22rem_1fr]">
        <form method="POST" action="{{ route('public-holidays.store') }}" class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">@csrf<h2 class="font-semibold">Tambah tanggal</h2><label class="mt-4 block text-sm font-semibold">Tanggal<input type="date" name="holiday_date" required class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"></label><label class="mt-4 block text-sm font-semibold">Nama hari libur<input name="name" required placeholder="Contoh: Idulfitri" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"></label><button class="mt-5 w-full rounded-xl bg-brand-600 px-5 py-3 text-sm font-semibold text-white">Simpan</button></form>
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Tanggal</th><th class="px-5 py-3">Hari libur</th><th></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($holidays as $holiday)<tr><td class="px-5 py-4 font-semibold">{{ $holiday->holiday_date->format('d/m/Y') }}</td><td class="px-5 py-4">{{ $holiday->name }}</td><td class="px-5 py-4 text-right"><form method="POST" action="{{ route('public-holidays.destroy', $holiday) }}">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-600">Hapus</button></form></td></tr>@empty<tr><td colspan="3" class="px-5 py-12 text-center text-slate-400">Belum ada tanggal merah.</td></tr>@endforelse</tbody></table><div class="border-t border-slate-100 px-5 py-4">{{ $holidays->links() }}</div></div>
    </div>
@endsection
