@extends('layouts.app')
@section('title', 'Detail Pengajuan Cuti | HRS Kampus')
@section('content')
    <a href="{{ route('leave-requests.index') }}" class="text-sm font-semibold text-brand-700">← Cuti & Persetujuan</a>
    <div class="mt-3 flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h1 class="text-3xl font-semibold">Detail Pengajuan Cuti</h1><p class="mt-2 text-sm text-slate-500">Diajukan {{ $leaveRequest->submitted_at->format('d/m/Y H.i') }}</p></div><span class="w-fit rounded-full bg-slate-100 px-4 py-2 text-sm font-semibold">{{ $leaveRequest->status->label() }}</span></div>

    <div class="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]">
        <div class="flex flex-col gap-5">
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold">Informasi Cuti atau Izin</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs uppercase text-slate-400">Jenis</dt><dd class="mt-1 font-semibold text-brand-700">{{ $leaveRequest->leave_type->label() }}</dd></div><div><dt class="text-xs uppercase text-slate-400">Pegawai</dt><dd class="mt-1 font-semibold">{{ $leaveRequest->employee->display_name }}</dd></div><div><dt class="text-xs uppercase text-slate-400">Pengganti</dt><dd class="mt-1 font-semibold">{{ $leaveRequest->replacement->display_name }}</dd></div><div><dt class="text-xs uppercase text-slate-400">Periode</dt><dd class="mt-1 font-semibold">{{ $leaveRequest->start_date->format('d/m/Y') }}–{{ $leaveRequest->end_date->format('d/m/Y') }}@if ($leaveRequest->leave_type->isPartialDay()) · {{ substr($leaveRequest->start_time, 0, 5) }}–{{ substr($leaveRequest->end_time, 0, 5) }}@endif</dd></div><div><dt class="text-xs uppercase text-slate-400">Durasi</dt><dd class="mt-1 font-semibold">{{ $leaveRequest->durationLabel() }}</dd></div>@if ($leaveRequest->supporting_document_path)<div><dt class="text-xs uppercase text-slate-400">Dokumen pendukung</dt><dd class="mt-1"><a href="{{ route('leave-requests.document', $leaveRequest) }}" class="text-sm font-semibold text-brand-700">Unduh surat dokter</a></dd></div>@endif<div class="sm:col-span-2"><dt class="text-xs uppercase text-slate-400">Alasan</dt><dd class="mt-2 whitespace-pre-line text-sm leading-6">{{ $leaveRequest->reason }}</dd></div></dl></section>

            @can('supervisorApprove', $leaveRequest)
                <section class="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 class="font-semibold text-amber-900">Keputusan Atasan Langsung</h2><form method="POST" action="{{ route('leave-requests.supervisor-approval', $leaveRequest) }}" class="mt-4">@csrf @method('PUT')<textarea name="notes" rows="3" placeholder="Catatan persetujuan atau alasan penolakan" class="w-full rounded-xl border border-amber-200 bg-white px-4 py-3 text-sm"></textarea><div class="mt-3 flex gap-2"><button name="decision" value="approve" class="rounded-xl bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white">Setujui & Kirim ke SDM</button><button name="decision" value="reject" class="rounded-xl bg-red-600 px-5 py-2.5 text-sm font-semibold text-white">Tolak</button></div></form></section>
            @endcan
            @can('hrApprove', $leaveRequest)
                <section class="rounded-2xl border border-sky-200 bg-sky-50 p-6"><h2 class="font-semibold text-sky-900">Keputusan SDM</h2><form method="POST" action="{{ route('leave-requests.hr-approval', $leaveRequest) }}" class="mt-4">@csrf @method('PUT')<textarea name="notes" rows="3" placeholder="Catatan persetujuan atau alasan penolakan" class="w-full rounded-xl border border-sky-200 bg-white px-4 py-3 text-sm"></textarea><div class="mt-3 flex gap-2"><button name="decision" value="approve" class="rounded-xl bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white">Setujui Cuti</button><button name="decision" value="reject" class="rounded-xl bg-red-600 px-5 py-2.5 text-sm font-semibold text-white">Tolak</button></div></form></section>
            @endcan
        </div>
        <aside class="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold">Alur Persetujuan</h2><div class="mt-5 flex flex-col gap-5">
            <div class="flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-full bg-brand-600 text-xs font-bold text-white">1</span><div><p class="font-semibold">Pengajuan pegawai</p><p class="mt-1 text-sm text-slate-500">Selesai · {{ $leaveRequest->submitted_at->format('d/m/Y H.i') }}</p></div></div>
            <div class="flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-full {{ $leaveRequest->supervisor_approved_at ? 'bg-brand-600 text-white' : 'bg-slate-100 text-slate-400' }} text-xs font-bold">2</span><div><p class="font-semibold">Atasan langsung</p><p class="mt-1 text-sm text-slate-500">{{ $leaveRequest->directSupervisor->display_name }}</p>@if ($leaveRequest->supervisor_notes)<p class="mt-2 rounded-lg bg-slate-50 p-2 text-sm">{{ $leaveRequest->supervisor_notes }}</p>@endif</div></div>
            <div class="flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-full {{ $leaveRequest->hr_approved_at ? 'bg-brand-600 text-white' : 'bg-slate-100 text-slate-400' }} text-xs font-bold">3</span><div><p class="font-semibold">SDM</p><p class="mt-1 text-sm text-slate-500">{{ $leaveRequest->hrApprover?->display_name ?? 'Menunggu tahap sebelumnya' }}</p>@if ($leaveRequest->hr_notes)<p class="mt-2 rounded-lg bg-slate-50 p-2 text-sm">{{ $leaveRequest->hr_notes }}</p>@endif</div></div>
        </div></aside>
    </div>
@endsection
