@extends('layouts.app')
@section('title', 'Payroll '. $payrollPeriod->period_date->format('m/Y').' | HRS Kampus')
@section('content')
    <a href="{{ route('payroll-periods.index') }}" class="text-sm font-semibold text-brand-700">← Daftar periode</a>
    <div class="mt-3 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 class="text-3xl font-semibold">Payroll {{ $payrollPeriod->period_date->locale('id')->translatedFormat('F Y') }}</h1><p class="mt-2 text-sm text-slate-500">Gaji otomatis dan komponen manual setiap pegawai.</p></div><div class="flex items-center gap-3"><span @class(['w-fit rounded-full px-3 py-1.5 text-xs font-semibold uppercase', 'bg-amber-50 text-amber-700' => $payrollPeriod->status === 'draft', 'bg-emerald-50 text-emerald-700' => $payrollPeriod->status !== 'draft'])>{{ $payrollPeriod->status === 'draft' ? 'Draft' : 'Final' }}</span><form method="POST" action="{{ route('payroll-periods.email-slips.store', $payrollPeriod) }}" onsubmit="return confirm('{{ $payrollPeriod->status === 'draft' ? 'Finalkan payroll dan kirim' : 'Kirim ulang' }} slip gaji ke seluruh karyawan yang memiliki email aktif?')">@csrf<button type="submit" class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">{{ $payrollPeriod->status === 'draft' ? 'Finalkan & Kirim Semua Slip' : 'Kirim Ulang Semua Slip' }}</button></form></div></div>
    <div class="mt-6 grid gap-4 md:grid-cols-3">@foreach (['gross_income' => 'Total Pendapatan', 'total_deductions' => 'Total Potongan', 'net_salary' => 'Total Gaji Bersih'] as $key => $label)<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-semibold">Rp {{ number_format((float) $summary[$key], 0, ',', '.') }}</p></div>@endforeach</div>
    <form method="GET" class="mt-6 flex max-w-xl gap-2"><input name="search" value="{{ $search }}" placeholder="Cari nama atau NIP..." class="w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm"><button class="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Cari</button></form>
    <div class="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[60rem] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Pegawai</th><th class="px-5 py-3">Gaji Pokok</th><th class="px-5 py-3">Pendapatan</th><th class="px-5 py-3">Potongan</th><th class="px-5 py-3">Gaji Bersih</th><th></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($payrolls as $payroll)<tr><td class="px-5 py-4"><p class="font-semibold">{{ $payroll->employee->display_name }}</p><p class="mt-1 text-xs text-slate-400">{{ $payroll->employee->nip }} · {{ $payroll->employee->department->name }}</p></td><td class="px-5 py-4">Rp {{ number_format((float) $payroll->base_salary, 0, ',', '.') }}</td><td class="px-5 py-4">Rp {{ number_format((float) $payroll->gross_income, 0, ',', '.') }}</td><td class="px-5 py-4 text-red-600">Rp {{ number_format((float) $payroll->total_deductions, 0, ',', '.') }}</td><td class="px-5 py-4 font-semibold text-brand-700">Rp {{ number_format((float) $payroll->net_salary, 0, ',', '.') }}</td><td class="px-5 py-4 text-right"><a href="{{ route('payrolls.show', $payroll) }}" class="font-semibold text-brand-700">Detail</a><a href="{{ route('payrolls.slip', $payroll) }}" class="ml-3 font-semibold text-slate-600">Slip</a>@if ($payrollPeriod->status === 'draft')<a href="{{ route('payrolls.edit', $payroll) }}" class="ml-3 font-semibold text-slate-600">Input</a>@endif</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-slate-400">Data payroll tidak ditemukan.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $payrolls->links() }}</div></div>
@endsection
